#!/usr/bin/env bash
# Write-time gate for the whole product tree.
#
# Two rule families:
#   1. Generated files are not edited by hand — the route tree (written by the router
#      plugin), every *.gen.ts / *.gen.tsx (written by the kit scaffold from the
#      manifest) and the generated database client. A hand edit is overwritten on the
#      next generate and hides the real problem until then.
#   2. The testing contract. The single source of truth is scripts/check-test-contract.mjs
#      — CI runs the same script; this hook only moves the failure to write time, where
#      the agent loop can fix it in the same breath instead of discovering it at PR time.
#
# Rules Biome cannot express and that need a diff against HEAD (counting, "only what
# this edit adds") go here too, through .claude/hooks/lib/added.sh — see that file.
#
# Contract: silent and exit 0 on pass. Exit 2 with diagnostics on stderr when the
# agent must act. Anything outside the repo returns before any work.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

payload="$(cat)"
file="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')"
[ -n "$file" ] || exit 0

cwd="$(printf '%s' "$payload" | jq -r '.cwd // empty')"
case "$file" in
  /*) abs="$file" ;;
  *) abs="${cwd:-$PWD}/$file" ;;
esac

# Cheap scope gate: string comparison only, for every edit outside this tree.
case "$abs" in
  "$ROOT"/*) ;;
  *) exit 0 ;;
esac
rel="${abs#"$ROOT"/}"

# ── 1. Generated files ────────────────────────────────────────────────────────
case "$rel" in
  apps/web/src/app/routeTree.gen.ts)
    echo "routeTree.gen.ts is generated by the router plugin — never edit it by hand. Change the route files under apps/web/src/app/routes/ and run \`yarn routes:generate\` (yarn dev / yarn build also regenerate it)." >&2
    exit 2
    ;;
  db/generated/*)
    echo "db/generated/ is the database client written by \`yarn db:generate\` — never edit it by hand. Change the schema under db/prisma/ and regenerate." >&2
    exit 2
    ;;
  *.gen.ts | *.gen.tsx)
    echo "$rel is generated by the kit scaffold from the project manifest — never edit it by hand. Change the module's module.json or .paperclip/project.manifest.json and re-run \`/scaffold\` (bin/scaffold.sh --update)." >&2
    exit 2
    ;;
esac

# ── 2. The testing contract ───────────────────────────────────────────────────
# Only source files can create contract debt — skip docs, configs, assets.
case "$rel" in
  *.ts | *.tsx) ;;
  *) exit 0 ;;
esac
[ -f "$ROOT/scripts/check-test-contract.mjs" ] || exit 0

out="$(node "$ROOT/scripts/check-test-contract.mjs" 2>&1)" && exit 0

{
  echo "testing contract violated by this edit's tree state:"
  echo ""
  echo "$out"
} >&2
exit 2
