// GENERATED by the paperclip-kit scaffold from .paperclip/project.manifest.json — do not edit.
// Re-run `bin/scaffold.sh --update` to regenerate; a module contributes through its module.json
// (`web.providers`, `web.gates`, `web.boot`, `web.settingsActions`).
import type { Boot, Gate, Provider, SettingsAction } from "~/app/kit.types";

export const KIT_PROVIDERS: Provider[] = [];
export const KIT_GATES: Gate[] = [];
export const KIT_BOOT: Boot[] = [];
export const KIT_SETTINGS_ACTIONS: SettingsAction[] = [];
