/**
 * GENERATED by the kit's scaffold from `.paperclip/project.manifest.json` — rewritten on
 * every `scaffold` and `scaffold --update`, so an edit here is lost on the next run. A
 * module contributes its handlers through `module.json` (`contracts.handlers`); base is
 * the empty manifest.
 */
import type { RequestHandler } from "msw";

/** Every opted-in module's mock handlers, spread after base's own in `mocks.ts`. */
export const KIT_HANDLERS: RequestHandler[] = [];
