/**
 * GENERATED by the kit's scaffold from `.paperclip/project.manifest.json` — rewritten on
 * every `scaffold` and `scaffold --update`, so an edit here is lost on the next run. A
 * module contributes to these lists through its `module.json` (`server.modules`,
 * `server.ports`, `server.rawBodyPaths`); base is the empty manifest.
 */
import type { Provider, Type } from "@nestjs/common";
import { AnalyticsConsoleProvider } from "./common/ports/analytics";
import { NotificationConsoleProvider } from "./common/ports/notification";
import { TelemetryConsoleProvider } from "./common/ports/telemetry";

/** The feature modules the manifest opted into, imported by `AppModule` after `PortsModule`. */
export const KIT_MODULES: Type<unknown>[] = [];

/** One provider per port. A port no module claims keeps its console default. */
export const KIT_PORTS: Provider[] = [NotificationConsoleProvider, AnalyticsConsoleProvider, TelemetryConsoleProvider];

/** Paths whose body must reach the handler unparsed — signed webhooks (`common/raw-body.ts`). */
export const KIT_RAW_BODY_PATHS: string[] = [];
