// GENERATED by paperclip-kit from .paperclip/project.manifest.json — do not edit; run /scaffold --update
import type { Boot, Gate, Provider, SettingsAction } from "~/kit.types";

export const KIT_PROVIDERS: Provider[] = [];
export const KIT_GATES: Gate[] = [];
export const KIT_BOOT: Boot[] = [];
export const KIT_SETTINGS_ACTIONS: SettingsAction[] = [];
