#!/usr/bin/env bash
# Per-worktree .env files.
#
# The port lives inside the .env of each app and the client bundle is built from
# that file, so process environment cannot override it. A worktree therefore
# needs its own .env — but the primary checkout's file is the source of truth
# and provisioning symlinks to it. The overlay breaks that symlink and writes a
# generated copy with only the keys wt.config.sh names changed.
#
# Regenerated on every `wt run`, so it cannot drift from the primary. Every
# generated file starts with WT_ENV_MARKER; anything without it is treated as
# hand-written and never overwritten.

WT_ENV_MARKER="# generated by scripts/wt"

# _wt_env_is_generated <file> — true when the file carries the marker header.
# `head -1 | grep -q` trips pipefail on SIGPIPE, so read the line first.
_wt_env_is_generated() {
  local first_line
  first_line="$(head -1 "$1" 2>/dev/null || true)"
  [[ "$first_line" == *"$WT_ENV_MARKER"* ]]
}

# _wt_env_escape <value> — makes a value safe as a sed replacement.
_wt_env_escape() {
  printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'
}

# _wt_env_set <file> <key> <value> — replaces the key's line, appending when absent.
# BSD and GNU sed disagree on in-place editing, so every rewrite goes through a
# temp file.
_wt_env_set() {
  local file="$1" key="$2" value="$3"
  if grep -qE "^${key}=" "$file"; then
    sed -E "s|^${key}=.*|${key}=$(_wt_env_escape "$value")|" "$file" >"$file.wt-tmp"
    mv "$file.wt-tmp" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

# _wt_env_swap_known_ports <file> <key> — rewrites every declared base port
# appearing in the key's value to this slot's equivalent, leaving the rest of
# the value (host, scheme, path) alone. For a single origin whose host must be
# preserved, and for a list of origins that may span several processes.
# config.sh guarantees no target equals another source, so the substitutions
# cannot cascade.
_wt_env_swap_known_ports() {
  local file="$1" key="$2"
  grep -qE "^${key}=" "$file" || return 0
  local before after script="" i
  before="$(grep -E "^${key}=" "$file" | head -1)"
  for ((i = 0; i < ${#WT_PROC_NAMES[@]}; i++)); do
    # \b is a GNU extension; anchor on a non-digit or end of line instead.
    script+="s|:${WT_PROC_BASES[$i]}([^0-9])|:${WT_PROC_PORTS[$i]}\\1|g"$'\n'
    script+="s|:${WT_PROC_BASES[$i]}\$|:${WT_PROC_PORTS[$i]}|"$'\n'
  done
  sed -E "/^${key}=/ {
${script}}" "$file" >"$file.wt-tmp"
  mv "$file.wt-tmp" "$file"
  after="$(grep -E "^${key}=" "$file" | head -1)"
  if [[ "$before" == "$after" ]]; then
    wt_warn "$key carries no declared base port — left as-is; check it points at this worktree"
  fi
}

# _wt_env_start <relative-path> — copies the primary's file into the worktree
# behind the marker header. Prints the destination path.
_wt_env_start() {
  local rel="$1"
  local src="$WT_PRIMARY_ROOT/$rel"
  local dest="$WT_ROOT/$rel"

  [[ -f "$src" ]] || wt_die "$src not found — the primary checkout has no $rel"

  if [[ -f "$dest" && ! -L "$dest" ]] && ! _wt_env_is_generated "$dest"; then
    wt_die "$dest is a hand-written file, not a generated overlay. Move it aside first."
  fi

  mkdir -p "$(dirname "$dest")"
  # Break the symlink before writing — never write through it into the primary.
  rm -f "$dest"
  {
    # shellcheck disable=SC2016  # the backticks are literal in the generated file
    printf '%s — rewritten on every `wt run`; edit %s instead\n' "$WT_ENV_MARKER" "$src"
    cat "$src"
  } >"$dest"

  printf '%s' "$dest"
}

# wt_env_overlay_files [database-url] <proc>... — the env files an overlay
# touches for these processes, unique, one per line: every selected process's
# env file, plus the database env file when a database URL is being set.
wt_env_overlay_files() {
  local database_url="$1"
  shift
  local proc i env
  {
    for proc in "$@"; do
      i="$(wt_proc_index "$proc")" || continue
      env="${WT_PROC_ENVS[$i]}"
      [[ -n "$env" ]] && printf '%s\n' "$env"
    done
    [[ -n "$database_url" ]] && printf '%s\n' "$WT_DB_ENV_FILE"
  } | awk '!seen[$0]++'
}

# wt_env_overlay [database-url] <proc>... — writes the overlays for the
# selected processes: each env file is copied from the primary once, then every
# selected process applies its keys, then the database URL lands in the
# database env file when the run has its own database.
wt_env_overlay() {
  local database_url="$1"
  shift

  local rel
  while IFS= read -r rel; do
    [[ -n "$rel" ]] || continue
    _wt_env_start "$rel" >/dev/null
  done < <(wt_env_overlay_files "$database_url" "$@")

  local proc i env dest keys key name spec value
  for proc in "$@"; do
    i="$(wt_proc_index "$proc")" || continue
    env="${WT_PROC_ENVS[$i]}"
    [[ -n "$env" ]] || continue
    dest="$WT_ROOT/$env"
    keys="${WT_PROC_KEYS[$i]}"
    while IFS= read -r key; do
      [[ -n "$key" ]] || continue
      name="${key%%=*}"
      spec="${key#*=}"
      [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] ||
        wt_die "WT_PROCS: '$key' in ${WT_PROC_NAMES[$i]}'s overlay keys is not KEY=<template>"
      if [[ "$spec" == "swap" ]]; then
        _wt_env_swap_known_ports "$dest" "$name"
      else
        value="$(wt_expand_template "$spec" "$i")"
        _wt_env_set "$dest" "$name" "$value"
      fi
    done < <(printf '%s\n' "$keys" | tr ',' '\n')
    wt_ok "$env — ${WT_PROC_NAMES[$i]} on port ${WT_PROC_PORTS[$i]}"
  done

  if [[ -n "$database_url" ]]; then
    _wt_env_set "$WT_ROOT/$WT_DB_ENV_FILE" "$WT_DB_URL_KEY" "$database_url"
    wt_ok "$WT_DB_ENV_FILE — $WT_DB_URL_KEY points at this worktree's database"
  fi
}

# wt_env_restore_symlinks — puts every generated overlay back to a symlink.
# Walks every env file the config could have overlaid, so a run that started
# fewer processes and a run that started more are both cleaned up.
wt_env_restore_symlinks() {
  local rel dest src
  while IFS= read -r rel; do
    [[ -n "$rel" ]] || continue
    dest="$WT_ROOT/$rel"
    src="$WT_PRIMARY_ROOT/$rel"
    [[ -f "$dest" && ! -L "$dest" ]] || continue
    _wt_env_is_generated "$dest" || continue
    [[ -f "$src" ]] || continue
    rm -f "$dest"
    ln -sfn "$src" "$dest"
    wt_ok "Restored $rel symlink to the primary checkout"
  done < <(wt_env_overlay_files "x" "${WT_PROC_NAMES[@]}")
}
