#!/usr/bin/env bash
# The generated Procfile and the Overmind instance that runs it.
#
# The Procfile lives in <worktree>/.wt/ together with the Overmind socket, so
# concurrent worktrees never share either. Process commands `cd` to absolute
# paths because Overmind roots itself at the Procfile's directory.
#
# Overmind (github.com/DarthSim/overmind) is the process manager: one tmux
# session per stack, one pane per process, attachable with `wt logs <proc>`.

wt_overmind_install_hint() {
  printf 'install it: brew install overmind (macOS), or go install github.com/DarthSim/overmind/v2@latest; it needs tmux'
}

# wt_overmind_socket — the socket lives in .wt/ so concurrent worktrees never
# share one. Unix socket paths cap at ~104 bytes on macOS (108 on Linux), and a
# deep worktree directory plus a long branch name can exceed that, so a path
# that would not bind falls back to a short per-worktree name under $TMPDIR.
WT_SOCKET_PATH_MAX=100
wt_overmind_socket() {
  local socket="$WT_STATE_DIR/overmind.sock"
  if [[ ${#socket} -le WT_SOCKET_PATH_MAX ]]; then
    printf '%s' "$socket"
    return 0
  fi
  local hash
  hash="$(printf '%s' "$WT_ROOT" | cksum | cut -d' ' -f1)"
  printf '%s/wt-%s.sock' "${TMPDIR:-/tmp}" "$hash"
}

# _wt_overmind_pids <procfile> — pids of every Overmind started for exactly
# this Procfile. `ps` rather than pgrep -a: on macOS -a means "include
# ancestors" and prints only pids, so the command line never arrives.
_wt_overmind_pids() {
  local procfile="$1"
  ps -axo pid=,args= 2>/dev/null |
    awk -v needle=" --procfile $procfile " 'index($0, "overmind start ") && index($0, needle) { print $1 }'
}

wt_overmind_title() {
  printf 'wt%s-%s' "$1" "$WT_SLUG"
}

# wt_procfile_line <proc> — the Procfile line for one process on the current slot.
wt_procfile_line() {
  local i cwd
  i="$(wt_proc_index "$1")" || return 1
  cwd="${WT_PROC_CWDS[$i]}"
  if [[ "$cwd" == "." ]]; then
    cwd="$WT_ROOT"
  else
    cwd="$WT_ROOT/$cwd"
  fi
  printf '%s: cd %s && %s\n' "$1" "$cwd" "$(wt_expand_template "${WT_PROC_CMDS[$i]}" "$i")"
}

# wt_write_procfile <slot> <proc>...
wt_write_procfile() {
  local slot="$1"
  shift
  local procfile="$WT_STATE_DIR/Procfile"

  mkdir -p "$WT_STATE_DIR"
  {
    # shellcheck disable=SC2016  # the backticks are literal in the generated file
    printf '# generated by scripts/wt for slot %s — rewritten on every `wt run`\n' "$slot"
    printf '# Each process reads its port from its .env overlay or its command line.\n'
    local proc
    for proc in "$@"; do
      wt_procfile_line "$proc"
    done
  } >"$procfile"

  wt_ok ".wt/Procfile written ($*)"
}

wt_overmind_is_running() {
  command -v overmind >/dev/null 2>&1 || return 1
  local socket
  socket="$(wt_overmind_socket)"
  [[ -S "$socket" ]] && overmind status -s "$socket" >/dev/null 2>&1
}

# wt_overmind_start <slot>
wt_overmind_start() {
  local slot="$1"
  local socket
  socket="$(wt_overmind_socket)"
  rm -f "$socket"

  # --no-port stops Overmind injecting its own $PORT, which would override the
  # port each app reads from its .env overlay.
  exec overmind start \
    --procfile "$WT_STATE_DIR/Procfile" \
    --socket "$socket" \
    --title "$(wt_overmind_title "$slot")" \
    --no-port
}

wt_overmind_stop() {
  local socket
  socket="$(wt_overmind_socket)"
  if [[ -S "$socket" ]] && command -v overmind >/dev/null 2>&1; then
    overmind quit -s "$socket" >/dev/null 2>&1 || true
    sleep 1
  fi
  # Only the Overmind started for this exact Procfile — the path is unique per
  # worktree, so nothing else can match. Killed by pid, never by name.
  local pid
  for pid in $(_wt_overmind_pids "$WT_STATE_DIR/Procfile"); do
    kill -TERM "$pid" 2>/dev/null || true
  done
  rm -f "$socket"
}

# wt_overmind_reap_orphans — kills every `wt`-started Overmind whose Procfile
# is gone. That is what a worktree deleted from under a running stack leaves
# behind (editor worktree hooks and a bare `git worktree remove` skip `wt stop`),
# and its children still hold the slot's ports. Only Procfiles written by wt
# (…/.wt/Procfile) are considered, so any other Overmind on the machine is
# never touched.
wt_overmind_reap_orphans() {
  local line pid procfile
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    pid="${line%% *}"
    procfile="${line##*--procfile }"
    procfile="${procfile%% *}"
    [[ "$procfile" == */.wt/Procfile ]] || continue
    [[ -f "$procfile" ]] && continue
    wt_warn "Reaping orphaned Overmind (pid $pid) — its worktree at ${procfile%/.wt/Procfile} is gone"
    kill -TERM "$pid" 2>/dev/null || true
  done < <(ps -axo pid=,args= 2>/dev/null | awk 'index($0, "overmind start ") && index($0, " --procfile ") { sub(/^ +/, ""); print }')
}
