#!/usr/bin/env bash
# Slots and the ports derived from them.
#
# Slot 0 is the primary checkout — the base ports every process declares in
# wt.config.sh, and what a plain checkout outside `wt run` binds. It is never
# handed out to a worktree. Slots 1-9 are worktrees. Every port is
# `base + WT_PORT_STRIDE * slot`; config.sh refuses bases whose slot ranges
# overlap.
#
# The table in docs/worktrees.md is generated by this arithmetic — change one
# and change the other.

WT_SLOT_MIN=1
WT_SLOT_MAX=9

# wt_ports <slot> — fills WT_PROC_PORTS for every process and sets WT_SLOT_CURRENT.
wt_ports() {
  local slot="$1" i
  local offset=$((WT_PORT_STRIDE * slot))
  # shellcheck disable=SC2034  # read by wt_expand_template in config.sh
  WT_SLOT_CURRENT="$slot"
  for ((i = 0; i < ${#WT_PROC_NAMES[@]}; i++)); do
    WT_PROC_PORTS[i]=$((WT_PROC_BASES[i] + offset))
  done
}

# wt_ports_summary — "server 3010 | web 5183 | metro 8310" for the current slot.
wt_ports_summary() {
  local i out=""
  for ((i = 0; i < ${#WT_PROC_NAMES[@]}; i++)); do
    [[ -n "$out" ]] && out+=" | "
    out+="${WT_PROC_NAMES[$i]} ${WT_PROC_PORTS[$i]}"
  done
  printf '%s' "$out"
}

# wt_slot_all_ports — every process's port on the current slot, one per line.
wt_slot_all_ports() {
  local i
  for ((i = 0; i < ${#WT_PROC_NAMES[@]}; i++)); do
    printf '%s\n' "${WT_PROC_PORTS[$i]}"
  done
}

# wt_slot_read [worktree-root] — prints the slot, or nothing when unallocated.
wt_slot_read() {
  local root="${1:-$WT_ROOT}"
  local file="$root/.wt/slot"
  [[ -f "$file" ]] || return 0
  tr -cd '0-9' <"$file"
}

# wt_slot_require — prints this worktree's slot, failing when it has none.
wt_slot_require() {
  local slot
  slot="$(wt_slot_read)"
  if [[ -z "$slot" ]]; then
    wt_die "No slot allocated for this worktree. Run: yarn wt provision"
  fi
  printf '%s' "$slot"
}

# wt_slot_taken — prints every slot currently claimed by a worktree, one per line.
# A worktree with no .wt/slot yet — every freshly added one — contributes nothing
# and must not make the function fail.
wt_slot_taken() {
  local path slot
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    slot="$(wt_slot_read "$path")"
    [[ -n "$slot" ]] || continue
    printf '%s\n' "$slot"
  # substr, not $2: a worktree path may contain spaces.
  done < <(git -C "$WT_PRIMARY_ROOT" worktree list --porcelain | awk '/^worktree /{print substr($0, 10)}')
  return 0
}

# wt_slot_allocate <worktree-root> — claims the lowest free slot and persists it.
#
# Two `wt create` runs can race between reading the taken set and writing the
# file. A lock directory under the shared git dir serialises them: mkdir is
# atomic on every filesystem this runs on. A trap releases it on every exit path,
# so a failure never strands it.
wt_slot_allocate() {
  local root="$1"
  local existing
  existing="$(wt_slot_read "$root")"
  if [[ -n "$existing" ]]; then
    printf '%s' "$existing"
    return 0
  fi

  local git_common lock_dir
  git_common="$(git -C "$WT_PRIMARY_ROOT" rev-parse --git-common-dir)"
  lock_dir="$(cd "$WT_PRIMARY_ROOT" && cd "$git_common" && pwd -P)/wt-slot.lock"

  local waited=0
  until mkdir "$lock_dir" 2>/dev/null; do
    if ((waited >= 30)); then
      wt_die "Timed out waiting for the slot lock at $lock_dir.
  If no other 'wt create' is running, remove it: rmdir $lock_dir"
    fi
    sleep 1
    waited=$((waited + 1))
  done
  # shellcheck disable=SC2064  # lock_dir must expand now, not when the trap fires
  trap "rmdir '$lock_dir' 2>/dev/null || true" EXIT
  # shellcheck disable=SC2064
  trap "rmdir '$lock_dir' 2>/dev/null || true; exit 130" INT TERM

  local taken candidate claimed=""
  taken="$(wt_slot_taken)"
  for ((candidate = WT_SLOT_MIN; candidate <= WT_SLOT_MAX; candidate++)); do
    if ! grep -qx "$candidate" <<<"$taken"; then
      mkdir -p "$root/.wt"
      printf '%s' "$candidate" >"$root/.wt/slot"
      claimed="$candidate"
      break
    fi
  done

  rmdir "$lock_dir" 2>/dev/null || true
  trap - EXIT INT TERM

  [[ -n "$claimed" ]] ||
    wt_die "All slots $WT_SLOT_MIN-$WT_SLOT_MAX are in use. Dispose of a worktree first."

  printf '%s' "$claimed"
}

wt_port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    [[ -n "$(ss -ltnH "sport = :$port" 2>/dev/null)" ]]
  else
    lsof -tiTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
  fi
}

# wt_kill_port_listeners <port>... — frees ports left bound after an unclean exit.
# Kills by port, never by process name, so nothing outside the slot is touched.
# Returns 1 when any port is still held afterwards.
wt_kill_port_listeners() {
  if ! command -v lsof >/dev/null 2>&1; then
    wt_warn "lsof not found — cannot clear stale listeners"
    return 0
  fi

  local port pids
  for port in "$@"; do
    pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
    [[ -n "$pids" ]] || continue
    wt_warn "Killing stale listener(s) on port $port (pid: ${pids//$'\n'/, })"
    # shellcheck disable=SC2086
    kill -TERM $pids 2>/dev/null || true
    sleep 0.5
    pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "$pids" ]]; then
      # shellcheck disable=SC2086
      kill -9 $pids 2>/dev/null || true
      sleep 0.5
    fi
  done

  local still_held=()
  for port in "$@"; do
    wt_port_in_use "$port" && still_held+=("$port")
  done
  if [[ ${#still_held[@]} -gt 0 ]]; then
    wt_fail "Still in use after cleanup: ${still_held[*]}"
    return 1
  fi
  return 0
}
