const path = require("node:path");
const { withProjectBuildGradle } = require("expo/config-plugins");

// `react-native-purchases` finds React Native's Android sources by looking for a prebuilt
// `node_modules/react-native/android` — gone since RN 0.71 — and then by walking five
// directories up from `android/`. Yarn hoists `react-native` to the repo root, six levels up
// from `apps/mobile/android`, so the walk stops one short and the Gradle build fails
// evaluating `:react-native-purchases`. Handing it the path through `rootProject.ext` skips
// the search: it is the first thing the module checks.
//
// A config plugin, not a patch: `android/` is generated by `expo prebuild` and thrown away,
// so the fix has to be part of what generates it. It is needed whenever React Native is
// hoisted above the app — which is every workspace layout this kit produces.
//
// A module cannot edit `app.config.js`, so add it there yourself:
//   plugins: [ …, "./plugins/withReactNativeAndroidRoot.cjs" ]
const MARKER = "reactNativeAndroidRoot";

module.exports = function withReactNativeAndroidRoot(config) {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      throw new Error("withReactNativeAndroidRoot only supports the Groovy android/build.gradle");
    }
    if (mod.modResults.contents.includes(MARKER)) {
      return mod;
    }

    const reactNativeDir = path.dirname(require.resolve("react-native/package.json", { paths: [__dirname] }));
    // Relative so the generated file stays valid wherever the checkout lives; the depth is
    // fixed by the workspace layout.
    const fromAndroidDir = path.relative(mod.modRequest.platformProjectRoot, reactNativeDir).split(path.sep).join("/");

    mod.modResults.contents += `\next.${MARKER} = new File(rootDir, "${fromAndroidDir}")\n`;
    return mod;
  });
};
